<?xml version='1.0'?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="pastern_joint" params="leg side">

  <xacro:if value="${side == 'R'}">
    <xacro:property name="pastern_origin_xyz" value="0 ${base_radius/2} 0"/>
  </xacro:if> 

  <xacro:if value="${side == 'L'}">
    <xacro:property name="pastern_origin_xyz" value="0 ${-base_radius/2} 0"/>
  </xacro:if> 

    <joint name="joint_${side}_pastern_${leg}" type="prismatic">
      <parent link="base_link_hoof_${leg}"/>
      <child link="${leg}_${side}_phalange"/>
      <origin xyz="${pastern_origin_xyz}" rpy="0 0 0" />
      <axis xyz="0 0 1" />
      <limit effort="30" velocity="1.0" lower="-0.02" upper="0.02" />
      <dynamics damping="0.7" friction="0" />
    </joint> 

  <gazebo>
      <plugin name="${side}_sea_j1" filename="libsea_plugin.so">
          <joint>joint_${side}_pastern_${leg}</joint>  
          <namespace>goat_robot</namespace>
          <stiffness>${pastern_joint_stifness}</stiffness>
          <pub_eltau>true</pub_eltau>
          <pub_state>true</pub_state>
          <sub_ext_tau>true</sub_ext_tau>
      </plugin>
  </gazebo>  

  </xacro:macro>



    
</robot>