<?xml version='1.0'?>

<robot name="goat_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:macro name="hip" params="leg">

      <xacro:if value="${leg == 'RF'}">
        <xacro:property name="origin_xyz" value="${base_length/2} ${base_width/2} 0"/>
      </xacro:if> 

      <xacro:if value="${leg == 'LF'}">
        <xacro:property name="origin_xyz" value="${-base_length/2} ${base_width/2} 0"/>
      </xacro:if> 

      <xacro:if value="${leg == 'RH'}">
        <xacro:property name="origin_xyz" value="${base_length/2} ${-base_width/2} 0"/>
      </xacro:if> 

      <xacro:if value="${leg == 'LH'}">
        <xacro:property name="origin_xyz" value="${-base_length/2} ${-base_width/2} 0"/>
      </xacro:if> 

    <joint name="joint_${leg}_hip" type="revolute">
      <parent link="base_link"/>
      <child link="${leg}_femur"/>
      <origin xyz="${origin_xyz}" rpy="0 ${pi/2} 0" />
      <axis xyz="0 0 1" />
      <limit effort="30" velocity="1.0" lower="-1" upper="1" />
    </joint> 

  </xacro:macro>


  <gazebo>
      <plugin name="${leg}_sea_j1" filename="libsea_plugin.so">
          <joint>joint_${leg}_hip</joint>  
          <namespace>goat_robot</namespace>
          <stiffness>${joint_stifness}</stiffness>
          <pub_eltau>true</pub_eltau>
          <pub_state>true</pub_state>
          <sub_ext_tau>true</sub_ext_tau>
      </plugin>
  </gazebo>
    
</robot>