<?xml version='1.0'?>

<robot name="goat_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="knee" params="leg" >
    
    <joint name="joint_${leg}_knee" type="revolute">
      <parent link="${leg}_femur"/>
      <child link="${leg}_shank"/>
      <origin xyz="${leg_length/2} 0 0" rpy="0 0 0" />
      <axis xyz="0 0 1" />
      <limit effort="30" velocity="1.0" lower="-1" upper="1" />
    </joint> 

  </xacro:macro>

  <gazebo>
        <plugin name="sea_j1" filename="libsea_plugin.so">
            <joint>joint_${leg}_knee</joint>  
            <namespace>goat_robot</namespace>
            <stiffness>${joint_stifness}</stiffness>
            <pub_eltau>true</pub_eltau>
            <pub_state>true</pub_state>
            <sub_ext_tau>true</sub_ext_tau>
        </plugin>
  </gazebo>

</robot>
