<?xml version='1.0'?>

<robot name="goat_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="hip_base" params="leg">

      <xacro:if value="${leg == 'RF'}">
        <xacro:property name="origin_xyz_hip" value="${base_length/2-0.033} ${base_width/2-0.033} ${-base_height/2}"/>
      </xacro:if> 

      <xacro:if value="${leg == 'LF'}">
        <xacro:property name="origin_xyz_hip" value="${-base_length/2+0.033} ${base_width/2-0.033} ${-base_height/2}"/>
      </xacro:if> 

      <xacro:if value="${leg == 'RH'}">
        <xacro:property name="origin_xyz_hip" value="${base_length/2 -0.033} ${-base_width/2+0.033} ${-base_height/2}"/>
      </xacro:if> 

      <xacro:if value="${leg == 'LH'}">
        <xacro:property name="origin_xyz_hip" value="${-base_length/2+0.033} ${-base_width/2+0.033} ${-base_height/2}"/>
      </xacro:if> 

      <joint name="${leg}_base" type="fixed">
        <origin xyz="${origin_xyz_hip}" rpy="0 0 ${pi/2}" />
        <parent link="base_link"/>
        <child link="${leg}_base_link"/>
      </joint> 

  </xacro:macro>
    
</robot>
