<?xml version='1.0'?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:macro name="claw" params="leg side ">

<!-- <xacro:if value="${side == 'R'}">
 <xacro:property name="claw_origin_xyz" value="0 ${phalange_radius/2} 0"/>
 <xacro:property name="mesh_claw" value="package://second_goat_description/meshes/stl/MirrorClaw.stl" />
</xacro:if> 

<xacro:if value="${side == 'L'}">
 <xacro:property name="claw_origin_xyz" value="0 ${-phalange_radius/2} 0"/>
 <xacro:property name="mesh_claw" value="package://second_goat_description/meshes/stl/Claw.stl" />
</xacro:if>  -->

<xacro:if value="${side == 'R'}">
  <link name="${leg}_${side}_claw">

    <visual>
      <origin xyz="0.05 -0.05 0.005" rpy="${-pi/2} 0 ${pi/2}" />
      <geometry>
          <mesh filename="package://second_goat_description/meshes/MirrorClaw.stl" scale="0.0012 0.0012 0.0012" />
      </geometry>
    </visual>

    <collision>
      <origin xyz="0.05 -0.05 0.005" rpy="${-pi/2} 0 ${pi/2}" />
      <geometry>
          <mesh filename="package://second_goat_description/meshes/MirrorClaw.stl" scale="0.0012 0.0012 0.0012" />
      </geometry>
    </collision>

    <inertial>
      <mass value="${claw_mass}"/>
      <origin xyz="0.01 ${phalange_radius/2} 0" rpy="0 0 0" />
      <inertia ixx="${claw_mass*(claw_width*claw_width+claw_height*claw_height)/12}" ixy="0.0" ixz="0.0" iyy="${claw_mass*(claw_length*claw_length+claw_height*claw_height)/12}" iyz="0.0" izz="${claw_mass*(claw_length*claw_length+claw_width*claw_width)/12}"/>
    </inertial>

  </link>
</xacro:if> 

<xacro:if value="${side == 'L'}">
  <link name="${leg}_${side}_claw">

    <visual>
      <origin xyz="0.05 -0.020 0.005" rpy="${-pi/2} 0 ${pi/2}" />
      <geometry>
          <mesh filename="package://second_goat_description/meshes/Claw.stl" scale="0.0012 0.0012 0.0012" />
      </geometry>
    </visual>

    <collision>
      <origin xyz="0.05 -0.020 0.005" rpy="${-pi/2} 0 ${pi/2}" />
      <geometry>
          <mesh filename="package://second_goat_description/meshes/Claw.stl" scale="0.0012 0.0012 0.0012" />
      </geometry>
    </collision>

    <inertial>
      <mass value="${claw_mass}"/>
      <origin xyz="0.01 ${-phalange_radius/2} 0" rpy="0 0 0" />
      <inertia ixx="${claw_mass*(claw_width*claw_width+claw_height*claw_height)/12}" ixy="0.0" ixz="0.0" iyy="${claw_mass*(claw_length*claw_length+claw_height*claw_height)/12}" iyz="0.0" izz="${claw_mass*(claw_length*claw_length+claw_width*claw_width)/12}"/>
    </inertial>

  </link>
</xacro:if> 

<gazebo reference="${leg}_${side}_claw">
        <material>Gazebo/WoodFloor</material>
  </gazebo> 
</xacro:macro>
</robot>